[2024-04-23T11:20:50.223+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-04-23T11:20:50.231+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-04-23T11:20:50.231+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:20:50.243+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-10 00:00:00+00:00
[2024-04-23T11:20:50.247+0000] {standard_task_runner.py:60} INFO - Started process 75588 to run task
[2024-04-23T11:20:50.249+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp38cqwbsx']
[2024-04-23T11:20:50.249+0000] {standard_task_runner.py:88} INFO - Job 247: Subtask gen_dates
[2024-04-23T11:20:50.272+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:20:50.299+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:20:50.413+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2024-04-23T11:20:50.413+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:20:51.701+0000] {python.py:202} INFO - Done. Returned value was: dates_20240310
[2024-04-23T11:20:51.713+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240310T000000, start_date=20240423T112050, end_date=20240423T112051
[2024-04-23T11:20:51.746+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:20:51.772+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T11:24:20.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-04-23T11:24:20.842+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-04-23T11:24:20.842+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:24:20.854+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-10 00:00:00+00:00
[2024-04-23T11:24:20.859+0000] {standard_task_runner.py:60} INFO - Started process 80777 to run task
[2024-04-23T11:24:20.861+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpac30jdih']
[2024-04-23T11:24:20.861+0000] {standard_task_runner.py:88} INFO - Job 269: Subtask gen_dates
[2024-04-23T11:24:20.884+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-10T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:24:20.914+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:24:21.036+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2024-04-23T11:24:21.037+0000] {logging_mixin.py:188} INFO - {'start': '2024-03-10 00:00:00+00:00', 'end': '2024-04-23 11:24:21'}
[2024-04-23T11:24:21.037+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:24:23.390+0000] {python.py:202} INFO - Done. Returned value was: dates_20240310
[2024-04-23T11:24:23.403+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240310T000000, start_date=20240423T112420, end_date=20240423T112423
[2024-04-23T11:24:23.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:24:23.455+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
