[2024-04-22T16:56:27.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T16:56:27.675+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T16:56:27.675+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:56:27.694+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-07 00:00:00+00:00
[2024-04-22T16:56:27.700+0000] {standard_task_runner.py:60} INFO - Started process 165642 to run task
[2024-04-22T16:56:27.706+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpz2vws1il']
[2024-04-22T16:56:27.708+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask read_equipements
[2024-04-22T16:56:27.805+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:56:27.875+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2024-04-22T16:56:27.876+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:56:27.882+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:56:27.882+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:56:27.887+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240307T000000, start_date=20240422T165627, end_date=20240422T165627
[2024-04-22T16:56:27.902+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task read_equipements ('NoneType' object has no attribute 'date'; 165642)
[2024-04-22T16:56:27.918+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:56:27.935+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:13:04.131+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T17:13:04.138+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T17:13:04.138+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:13:04.151+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-07 00:00:00+00:00
[2024-04-22T17:13:04.154+0000] {standard_task_runner.py:60} INFO - Started process 182670 to run task
[2024-04-22T17:13:04.156+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpj135a93l']
[2024-04-22T17:13:04.157+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask read_equipements
[2024-04-22T17:13:04.188+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:13:04.239+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2024-04-22T17:13:04.240+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:13:06.369+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:13:06.369+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:13:06.372+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240307T000000, start_date=20240422T171304, end_date=20240422T171306
[2024-04-22T17:13:06.381+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task read_equipements ('NoneType' object has no attribute 'date'; 182670)
[2024-04-22T17:13:06.414+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:13:06.426+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:17:21.084+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:17:21.092+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:17:21.092+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:17:21.107+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-07 00:00:00+00:00
[2024-04-22T18:17:21.110+0000] {standard_task_runner.py:60} INFO - Started process 235442 to run task
[2024-04-22T18:17:21.112+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmppq411f2p']
[2024-04-22T18:17:21.113+0000] {standard_task_runner.py:88} INFO - Job 101: Subtask read_equipements
[2024-04-22T18:17:21.142+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:17:21.177+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:17:21.203+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2024-04-22T18:17:21.204+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:17:21.204+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-07 00:00:00+00:00', '2024-03-07 00:00:00+00:00']
[2024-04-22T18:17:23.194+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:17:23.210+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240307T000000, start_date=20240422T181721, end_date=20240422T181723
[2024-04-22T18:17:23.249+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:17:23.272+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-07T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:17:23.277+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:25:40.713+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:25:40.721+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:25:40.722+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:25:40.737+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-07 00:00:00+00:00
[2024-04-22T18:25:40.740+0000] {standard_task_runner.py:60} INFO - Started process 245867 to run task
[2024-04-22T18:25:40.743+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpsv7v96e1']
[2024-04-22T18:25:40.744+0000] {standard_task_runner.py:88} INFO - Job 154: Subtask read_equipements
[2024-04-22T18:25:40.776+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:25:40.819+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:25:40.842+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2024-04-22T18:25:40.842+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:25:40.843+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-07 00:00:00+00:00', '2024-03-07 00:00:00+00:00']
[2024-04-22T18:25:43.010+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:25:43.028+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240307T000000, start_date=20240422T182540, end_date=20240422T182543
[2024-04-22T18:25:43.080+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:25:43.104+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-07T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:25:43.109+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:27:34.155+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:27:34.163+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2024-04-22T18:27:34.164+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:27:34.180+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-07 00:00:00+00:00
[2024-04-22T18:27:34.183+0000] {standard_task_runner.py:60} INFO - Started process 248230 to run task
[2024-04-22T18:27:34.186+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpkl7iydkm']
[2024-04-22T18:27:34.186+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask read_equipements
[2024-04-22T18:27:34.215+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-07T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:27:34.253+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:27:34.276+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2024-04-22T18:27:34.278+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:27:34.278+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-07 00:00:00+00:00', '2024-03-07 00:00:00+00:00']
[2024-04-22T18:27:36.273+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:27:36.290+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240307T000000, start_date=20240422T182734, end_date=20240422T182736
[2024-04-22T18:27:36.324+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:27:36.352+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-07T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:27:36.357+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
