[2024-04-23T11:21:28.664+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-04-23T11:21:28.671+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-04-23T11:21:28.671+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:21:28.685+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-17 00:00:00+00:00
[2024-04-23T11:21:28.690+0000] {standard_task_runner.py:60} INFO - Started process 76660 to run task
[2024-04-23T11:21:28.693+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpzk34obxm']
[2024-04-23T11:21:28.694+0000] {standard_task_runner.py:88} INFO - Job 254: Subtask gen_dates
[2024-04-23T11:21:28.720+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:21:28.750+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:21:28.870+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-04-23T11:21:28.871+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:21:31.748+0000] {python.py:202} INFO - Done. Returned value was: dates_20240317
[2024-04-23T11:21:31.763+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240317T000000, start_date=20240423T112128, end_date=20240423T112131
[2024-04-23T11:21:31.795+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:21:31.812+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T11:24:53.612+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-04-23T11:24:53.618+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-04-23T11:24:53.618+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:24:53.628+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-17 00:00:00+00:00
[2024-04-23T11:24:53.632+0000] {standard_task_runner.py:60} INFO - Started process 81695 to run task
[2024-04-23T11:24:53.634+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpqa5b99ld']
[2024-04-23T11:24:53.634+0000] {standard_task_runner.py:88} INFO - Job 276: Subtask gen_dates
[2024-04-23T11:24:53.656+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-17T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:24:53.681+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:24:53.797+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-04-23T11:24:53.797+0000] {logging_mixin.py:188} INFO - {'start': '2024-03-17 00:00:00+00:00', 'end': '2024-04-23 11:24:53'}
[2024-04-23T11:24:53.797+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:24:55.586+0000] {python.py:202} INFO - Done. Returned value was: dates_20240317
[2024-04-23T11:24:55.607+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240317T000000, start_date=20240423T112453, end_date=20240423T112455
[2024-04-23T11:24:55.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:24:55.673+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
