[2024-04-23T11:21:08.426+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-04-23T11:21:08.431+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-04-23T11:21:08.431+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:21:08.443+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-13 00:00:00+00:00
[2024-04-23T11:21:08.448+0000] {standard_task_runner.py:60} INFO - Started process 76105 to run task
[2024-04-23T11:21:08.452+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpn9pncusx']
[2024-04-23T11:21:08.453+0000] {standard_task_runner.py:88} INFO - Job 250: Subtask gen_dates
[2024-04-23T11:21:08.491+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:21:08.523+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:21:08.637+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-13T00:00:00+00:00'
[2024-04-23T11:21:08.638+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:21:11.679+0000] {python.py:202} INFO - Done. Returned value was: dates_20240313
[2024-04-23T11:21:11.698+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240313T000000, start_date=20240423T112108, end_date=20240423T112111
[2024-04-23T11:21:11.720+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:21:11.737+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T11:24:34.649+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-04-23T11:24:34.655+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-04-23T11:24:34.655+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:24:34.667+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-13 00:00:00+00:00
[2024-04-23T11:24:34.670+0000] {standard_task_runner.py:60} INFO - Started process 81178 to run task
[2024-04-23T11:24:34.673+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpew4er5ok']
[2024-04-23T11:24:34.673+0000] {standard_task_runner.py:88} INFO - Job 272: Subtask gen_dates
[2024-04-23T11:24:34.694+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-13T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:24:34.721+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:24:34.848+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-13T00:00:00+00:00'
[2024-04-23T11:24:34.849+0000] {logging_mixin.py:188} INFO - {'start': '2024-03-13 00:00:00+00:00', 'end': '2024-04-23 11:24:34'}
[2024-04-23T11:24:34.849+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:24:36.370+0000] {python.py:202} INFO - Done. Returned value was: dates_20240313
[2024-04-23T11:24:36.381+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240313T000000, start_date=20240423T112434, end_date=20240423T112436
[2024-04-23T11:24:36.414+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:24:36.428+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
