[2024-04-22T16:56:40.328+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T16:56:40.334+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T16:56:40.334+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:56:40.346+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-11 00:00:00+00:00
[2024-04-22T16:56:40.348+0000] {standard_task_runner.py:60} INFO - Started process 165959 to run task
[2024-04-22T16:56:40.351+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpbgvlaxxe']
[2024-04-22T16:56:40.351+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask read_equipements
[2024-04-22T16:56:40.379+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:56:40.457+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-04-22T16:56:40.458+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:56:40.465+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:56:40.465+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:56:40.472+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240311T000000, start_date=20240422T165640, end_date=20240422T165640
[2024-04-22T16:56:40.482+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task read_equipements ('NoneType' object has no attribute 'date'; 165959)
[2024-04-22T16:56:40.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:56:40.537+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:13:23.720+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T17:13:23.732+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T17:13:23.732+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:13:23.752+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-11 00:00:00+00:00
[2024-04-22T17:13:23.760+0000] {standard_task_runner.py:60} INFO - Started process 183139 to run task
[2024-04-22T17:13:23.764+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp7aobei0f']
[2024-04-22T17:13:23.766+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask read_equipements
[2024-04-22T17:13:23.801+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:13:23.855+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-04-22T17:13:23.856+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:13:25.823+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:13:25.823+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:13:25.826+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240311T000000, start_date=20240422T171323, end_date=20240422T171325
[2024-04-22T17:13:25.836+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 72 for task read_equipements ('NoneType' object has no attribute 'date'; 183139)
[2024-04-22T17:13:25.861+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:13:25.873+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:17:39.730+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:17:39.740+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:17:39.740+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:17:39.754+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-11 00:00:00+00:00
[2024-04-22T18:17:39.757+0000] {standard_task_runner.py:60} INFO - Started process 235852 to run task
[2024-04-22T18:17:39.760+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp9ekd6tt0']
[2024-04-22T18:17:39.761+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask read_equipements
[2024-04-22T18:17:39.789+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:17:39.824+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:17:39.845+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-04-22T18:17:39.846+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:17:39.846+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-11 00:00:00+00:00', '2024-03-11 00:00:00+00:00']
[2024-04-22T18:17:41.924+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:17:41.941+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240311T000000, start_date=20240422T181739, end_date=20240422T181741
[2024-04-22T18:17:41.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:17:42.005+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-11T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:17:42.011+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:25:59.173+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:25:59.182+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:25:59.183+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:25:59.196+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-11 00:00:00+00:00
[2024-04-22T18:25:59.199+0000] {standard_task_runner.py:60} INFO - Started process 246301 to run task
[2024-04-22T18:25:59.201+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp09l6vdz7']
[2024-04-22T18:25:59.202+0000] {standard_task_runner.py:88} INFO - Job 158: Subtask read_equipements
[2024-04-22T18:25:59.229+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:25:59.268+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:25:59.288+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-04-22T18:25:59.289+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:25:59.289+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-11 00:00:00+00:00', '2024-03-11 00:00:00+00:00']
[2024-04-22T18:26:01.636+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:26:01.653+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240311T000000, start_date=20240422T182559, end_date=20240422T182601
[2024-04-22T18:26:01.700+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:26:01.726+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-11T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:26:01.731+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:28:35.680+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:28:35.689+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-04-22T18:28:35.690+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:28:35.704+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-11 00:00:00+00:00
[2024-04-22T18:28:35.707+0000] {standard_task_runner.py:60} INFO - Started process 249535 to run task
[2024-04-22T18:28:35.709+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmppsh3ios3']
[2024-04-22T18:28:35.710+0000] {standard_task_runner.py:88} INFO - Job 169: Subtask read_equipements
[2024-04-22T18:28:35.739+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-11T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:28:35.780+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:28:35.805+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-04-22T18:28:35.806+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:28:35.807+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-11 00:00:00+00:00', '2024-03-11 00:00:00+00:00']
[2024-04-22T18:28:37.931+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:28:37.950+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240311T000000, start_date=20240422T182835, end_date=20240422T182837
[2024-04-22T18:28:38.007+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:28:38.036+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-11T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:28:38.043+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
